### ISSUE TITLE
Study: RuntimeError raised when using Async in an IPython environment

### ISSUE THREAD

**Issue by reiniervlinschoten** [reiniervlinschoten/castoredc_api#41]
When running the package in an IPython console (Spyder3, Jupiter Notebooks) a RuntimeError is raised:

```python
Downloading Study Structure.
Mapping Study Structure: 100%|██████████| 115/115 [00:00<?, ?it/s]Downloading Field Dependencies

Traceback (most recent call last):

  File "C:\Users\117706\AppData\Local\Temp/ipykernel_1152/2353807798.py", line 1, in <module>
    test = study.map_data()

  File "C:\Users\117706\anaconda3\envs\TestCastorEDC\lib\site-packages\castoredc_api\study\castor_study.py", line 114, in map_data
    self.map_structure()

  File "C:\Users\117706\anaconda3\envs\TestCastorEDC\lib\site-packages\castoredc_api\study\castor_study.py", line 108, in map_structure
    self.__map_field_dependencies()

  File "C:\Users\117706\anaconda3\envs\TestCastorEDC\lib\site-packages\castoredc_api\study\castor_study.py", line 229, in __map_field_dependencies
    dependencies = self.client.all_field_dependencies()

  File "C:\Users\117706\anaconda3\envs\TestCastorEDC\lib\site-packages\castoredc_api\client\castoredc_api_client.py", line 264, in all_field_dependencies
    return self.retrieve_all_data_by_endpoint(

  File "C:\Users\117706\anaconda3\envs\TestCastorEDC\lib\site-packages\castoredc_api\client\castoredc_api_client.py", line 808, in retrieve_all_data_by_endpoint
    return self.retrieve_multiple_pages(url=url, params=params, data_name=data_name)

  File "C:\Users\117706\anaconda3\envs\TestCastorEDC\lib\site-packages\castoredc_api\client\castoredc_api_client.py", line 818, in retrieve_multiple_pages
    rest_response = self.retrieve_rest_of_pages(url=url, params=params, pages=pages)

  File "C:\Users\117706\anaconda3\envs\TestCastorEDC\lib\site-packages\castoredc_api\client\castoredc_api_client.py", line 852, in retrieve_rest_of_pages
    responses = asyncio.run(self.async_get(url=url, params=params))

  File "C:\Users\117706\anaconda3\envs\TestCastorEDC\lib\asyncio\runners.py", line 33, in run
    raise RuntimeError(

RuntimeError: asyncio.run() cannot be called from a running event loop
```

This is happening because an async loop is started by these consoles. 

Can't use [nest_asyncio](https://github.com/erdewit/nest_asyncio) as this will give errors in the console and will give [error prone code](https://bugs.python.org/issue33523).

**Comment by reiniervlinschoten** [comment]
Because I couldn't (and can't) seem to figure out how to await the coroutine that returns the responses.

For example
```python
        try:
            # Running eventloop, can't use async code
            loop = asyncio.get_running_loop()
            task = self.async_get(url=url, params=params)
            loop.create_task(task)
            responses = [self.handle_response(response) for response in task]
```

Will give an error as the task is not awaited and the sync code tries to iterate over the coroutine instead of the responses returned by the coroutine.
Moreover, we can't use async in this part of the code because it is sync code.
Maybe I am missing something, but the internet/Google isn't helping me either.

asyncio.run_coroutine_threadsafe doesn´t work either±
Nope, sadly this results in a timeout error when specifying a timeout in future.result or just nothing happening when not specifying a TimeOut.

See also https://github.com/reiniervlinschoten/castoredc_api/pull/39#discussion_r740389868_ for discussion
